# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6c5e5683-96e3-4945-ad09-52d4bf6ddf62";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptnixos".device = "/dev/disk/by-uuid/ef710db1-3bf4-43f4-baf8-3cd21ce7b955";

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/135165e2-3083-4fd8-a04c-5365d7142b5f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptdata".device = "/dev/disk/by-uuid/7c470d46-3d11-43b5-b45b-928764fa207b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9E83-16F7";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp111s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
